"""Dashboard, leaderboard, and static HTML report generation.

Reports consume ``RunResult`` objects (or JSON dictionaries with the same
fields) and intentionally make no assumptions about a model provider.  The
same code therefore works for the built-in Random/RuleBased/Scripted/Mock
agents and for future providers.  Every value in a report is derived from
public run metrics; private chain-of-thought is never requested or rendered.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import asdict, is_dataclass
import html
import json
from pathlib import Path
from statistics import mean
from typing import Any, Iterable, Mapping, Sequence

from .replay import Replay, ReplayViewer, _jsonable


def _iter_runs(value: Any) -> list[Any]:
    """Accept a run sequence, a TournamentResult, or a single run."""

    if value is None:
        return []
    if isinstance(value, Mapping):
        for key in ("runs", "results", "run_results"):
            candidate = value.get(key)
            if isinstance(candidate, Sequence) and not isinstance(candidate, (str, bytes)):
                return list(candidate)
        return [value]
    for key in ("runs", "results", "run_results"):
        candidate = getattr(value, key, None)
        if isinstance(candidate, Sequence) and not isinstance(candidate, (str, bytes)):
            return list(candidate)
    if isinstance(value, Iterable) and not isinstance(value, (str, bytes)):
        try:
            return list(value)
        except TypeError:
            pass
    return [value]


def _field(value: Any, *names: str, default: Any = None) -> Any:
    if value is None:
        return default
    for name in names:
        if isinstance(value, Mapping) and name in value:
            return value[name]
        if hasattr(value, name):
            return getattr(value, name)
    return default


def _as_mapping(value: Any) -> Mapping[str, Any]:
    if isinstance(value, Mapping):
        return value
    if hasattr(value, "to_dict") and callable(value.to_dict):
        try:
            result = value.to_dict(include_trace=False)
        except TypeError:
            try:
                result = value.to_dict()
            except Exception:
                result = None
        if isinstance(result, Mapping):
            return result
    if is_dataclass(value):
        try:
            result = asdict(value)
            if isinstance(result, Mapping):
                return result
        except Exception:
            pass
    return {}


def _number(value: Any, default: float = 0.0) -> float:
    try:
        if value is None or value == "":
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def _int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _metric(item: Any, metrics: Mapping[str, Any], *names: str, default: Any = None) -> Any:
    value = _field(item, *names, default=None)
    if value is not None:
        return value
    for name in names:
        if name in metrics:
            return metrics[name]
    return default


def _extract_steps(item: Any) -> int:
    direct = _field(item, "step_count", "steps", default=None)
    if isinstance(direct, Sequence) and not isinstance(direct, (str, bytes)):
        return len(direct)
    if direct is not None:
        return _int(direct)
    trace = _field(item, "trace", "agent_trace", default=None)
    if trace is not None:
        steps = _field(trace, "step_count", "steps", "events", default=0)
        if isinstance(steps, Sequence) and not isinstance(steps, (str, bytes)):
            return len(steps)
        return _int(steps)
    return 0


def _normalise_failures(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, Mapping):
        # A failure map can be useful in a JSON result; preserve labels and
        # avoid exposing a potentially large payload in the report.
        return [str(k) for k, v in value.items() if v or v == 0]
    if isinstance(value, Sequence):
        output: list[str] = []
        for failure in value:
            if isinstance(failure, Mapping):
                label = failure.get("type", failure.get("category", failure.get("name", failure)))
                output.append(str(label))
            else:
                output.append(str(failure))
        return output
    return [str(value)]


def normalise_run(run: Any) -> dict[str, Any]:
    """Flatten a RunResult-like value into the report schema.

    The schema is deliberately explicit and stable so reports generated by a
    new runner can still be consumed by older dashboard code.
    """

    raw = _as_mapping(run)
    metrics = _field(run, "metrics", default=None)
    if not isinstance(metrics, Mapping):
        metrics = raw.get("metrics", {}) if isinstance(raw.get("metrics", {}), Mapping) else {}
    task = _field(run, "task", default=None)
    task_map = _as_mapping(task)
    agent = _field(run, "agent", default=None)
    agent_map = _as_mapping(agent)
    success = _metric(run, metrics, "success", "succeeded", default=None)
    if success is None:
        status = str(_field(run, "status", default=""))
        success = status.lower() in {"success", "succeeded", "completed_success", "passed"}
    failures = _normalise_failures(_field(run, "failures", "failure_taxonomy", default=metrics.get("failures")))
    steps = _extract_steps(run)
    category = _metric(run, metrics, "category", "task_category", default=None)
    if category is None:
        category = task_map.get("category", task_map.get("task_type", task_map.get("type", "generic")))
    agent_id = _field(run, "agent_id", default=None) or agent_map.get("id", agent_map.get("name", "unknown"))
    task_id = _field(run, "task_id", default=None) or task_map.get("task_id", task_map.get("id", "unknown"))
    invalid = _metric(run, metrics, "invalid_actions", "invalid_action_count", default=0)
    retries = _metric(run, metrics, "retries", "retry_count", default=0)
    latency = _metric(run, metrics, "latency_ms", "latency", "total_latency", default=0.0)
    if latency == 0:
        trace = _field(run, "trace", "agent_trace", default=None)
        latency = _field(trace, "total_latency", default=0.0)
        # Trace latency is usually seconds; an explicit latency_ms wins above.
        if latency and _field(run, "latency_ms", default=None) is None:
            latency = _number(latency) * 1000.0
    tokens = _metric(run, metrics, "token_usage", "tokens", "tokens_used", default=0)
    cost = _metric(run, metrics, "estimated_cost", "cost", default=0.0)
    score = _metric(run, metrics, "score", default=_field(run, "score", default=0.0))
    recovery = _metric(run, metrics, "recovery_ability", "recovery_rate", "recovered", default=None)
    if recovery is None:
        # A conservative fallback: a successful run with a failure/retry event
        # demonstrates recovery; a clean success is not evidence either way.
        recovery = 1.0 if success and (failures or _number(retries) > 0) else None
    efficiency = _metric(run, metrics, "tool_efficiency", "efficiency", default=None)
    if efficiency is None and steps:
        efficiency = 1.0 / steps if success else 0.0
    synthetic = _metric(run, metrics, "synthetic", default=None)
    if synthetic is None:
        synthetic = _field(run, "synthetic", default=agent_map.get("synthetic", True))
    return {
        "run_id": str(_field(run, "run_id", "id", default=raw.get("run_id", ""))),
        "agent_id": str(agent_id),
        "task_id": str(task_id),
        "category": str(category),
        "seed": _field(run, "seed", default=raw.get("seed")),
        "status": str(_field(run, "status", default=raw.get("status", "unknown"))),
        "success": bool(success),
        "score": _number(score),
        "steps": steps,
        "invalid_actions": _int(invalid),
        "retries": _int(retries),
        "recovery_ability": None if recovery is None else _number(recovery),
        "tool_efficiency": None if efficiency is None else _number(efficiency),
        "latency_ms": _number(latency),
        "token_usage": _int(tokens),
        "estimated_cost": _number(cost),
        "failures": failures,
        "synthetic": bool(synthetic),
        "error": _field(run, "error", default=None),
    }


def _safe_mean(values: Iterable[float]) -> float:
    values = list(values)
    return float(mean(values)) if values else 0.0


def _aggregate_group(rows: list[dict[str, Any]], key: str, value: str) -> dict[str, Any]:
    selected = [row for row in rows if row.get(key) == value]
    count = len(selected)
    successes = sum(1 for row in selected if row["success"])
    recovery_values = [row["recovery_ability"] for row in selected if row["recovery_ability"] is not None]
    return {
        key: value,
        "runs": count,
        "successes": successes,
        "success_rate": successes / count if count else 0.0,
        "reliability": successes / count if count else 0.0,
        "average_score": _safe_mean(row["score"] for row in selected),
        "average_steps": _safe_mean(row["steps"] for row in selected),
        "invalid_actions": sum(row["invalid_actions"] for row in selected),
        "retries": sum(row["retries"] for row in selected),
        "recovery_ability": _safe_mean(recovery_values) if recovery_values else None,
        "tool_efficiency": _safe_mean(row["tool_efficiency"] for row in selected if row["tool_efficiency"] is not None),
        "average_latency_ms": _safe_mean(row["latency_ms"] for row in selected),
        "token_usage": sum(row["token_usage"] for row in selected),
        "estimated_cost": sum(row["estimated_cost"] for row in selected),
        "synthetic": all(row["synthetic"] for row in selected) if selected else True,
    }


def aggregate_metrics(runs: Iterable[Any]) -> dict[str, Any]:
    """Calculate dashboard metrics by agent, category, and failure type."""

    rows = [normalise_run(run) for run in _iter_runs(runs)]
    agents = sorted({row["agent_id"] for row in rows})
    categories = sorted({row["category"] for row in rows})
    failure_counts: Counter[str] = Counter()
    for row in rows:
        failure_counts.update(row["failures"])
    success_count = sum(1 for row in rows if row["success"])
    recovery_values = [row["recovery_ability"] for row in rows if row["recovery_ability"] is not None]
    overall = {
        "runs": len(rows),
        "successes": success_count,
        "success_rate": success_count / len(rows) if rows else 0.0,
        "reliability": success_count / len(rows) if rows else 0.0,
        "average_score": _safe_mean(row["score"] for row in rows),
        "average_steps": _safe_mean(row["steps"] for row in rows),
        "invalid_actions": sum(row["invalid_actions"] for row in rows),
        "retries": sum(row["retries"] for row in rows),
        "recovery_ability": _safe_mean(recovery_values) if recovery_values else None,
        "tool_efficiency": _safe_mean(row["tool_efficiency"] for row in rows if row["tool_efficiency"] is not None),
        "average_latency_ms": _safe_mean(row["latency_ms"] for row in rows),
        "token_usage": sum(row["token_usage"] for row in rows),
        "estimated_cost": sum(row["estimated_cost"] for row in rows),
    }
    agent_rows = [_aggregate_group(rows, "agent_id", agent) for agent in agents]
    category_rows = [_aggregate_group(rows, "category", category) for category in categories]
    # Keep the failure taxonomy deterministic and useful for an empty report.
    failures = [{"type": key, "count": count} for key, count in sorted(failure_counts.items(), key=lambda pair: (-pair[1], pair[0]))]
    return {
        "overall": overall,
        "agents": agent_rows,
        "categories": category_rows,
        "failure_breakdown": failures,
        "runs": rows,
    }


def leaderboard(runs: Iterable[Any]) -> list[dict[str, Any]]:
    """Return agent aggregates in tournament/ranking order.

    Ordering favours success rate, then score, then fewer steps and invalid
    actions.  The tie-breakers make a tournament deterministic across seeds.
    """

    rows = aggregate_metrics(runs)["agents"]
    rows.sort(key=lambda row: (-row["success_rate"], -row["average_score"], row["average_steps"], row["invalid_actions"], row["agent_id"]))
    for index, row in enumerate(rows, 1):
        row["rank"] = index
    return rows


def build_dashboard_data(runs: Iterable[Any]) -> dict[str, Any]:
    """Alias with a descriptive name for API/CLI consumers."""

    data = aggregate_metrics(runs)
    data["leaderboard"] = sorted(
        data["agents"],
        key=lambda row: (-row["success_rate"], -row["average_score"], row["average_steps"], row["invalid_actions"], row["agent_id"]),
    )
    for index, row in enumerate(data["leaderboard"], 1):
        row["rank"] = index
    return data


def _pct(value: Any) -> str:
    return f"{_number(value) * 100:.1f}%"


def _metric_card(label: str, value: str, detail: str = "") -> str:
    return f'<div class="metric"><div class="metric-label">{html.escape(label)}</div><div class="metric-value">{html.escape(value)}</div><div class="metric-detail">{html.escape(detail)}</div></div>'


def render_dashboard_html(
    runs: Iterable[Any],
    *,
    title: str = "Agent Arena Dashboard",
    replay_links: Mapping[str, str] | None = None,
) -> str:
    """Render a self-contained HTML dashboard with ranking and breakdowns."""

    data = build_dashboard_data(_iter_runs(runs))
    overall = data["overall"]
    replay_links = replay_links or {}
    cards = "".join(
        [
            _metric_card("Success", _pct(overall["success_rate"]), f'{overall["successes"]}/{overall["runs"]} runs'),
            _metric_card("Efficiency", f'{overall["average_steps"]:.2f} steps', f'{overall["tool_efficiency"]:.3f} tool score' if overall["tool_efficiency"] else "no efficiency data"),
            _metric_card("Reliability", _pct(overall["reliability"]), "successful task completion"),
            _metric_card("Recovery", "n/a" if overall["recovery_ability"] is None else _pct(overall["recovery_ability"]), f'{overall["retries"]} retries'),
            _metric_card("Latency", f'{overall["average_latency_ms"]:.1f} ms', f'{overall["token_usage"]} tokens'),
            _metric_card("Cost", f'${overall["estimated_cost"]:.4f}', "estimated; synthetic runs are $0"),
        ]
    )
    board_rows = []
    for row in data["leaderboard"]:
        board_rows.append(
            "<tr>"
            f'<td class="rank">{row["rank"]}</td><td><strong>{html.escape(row["agent_id"])}</strong>'
            f'{" <span class=\"synthetic\">synthetic</span>" if row["synthetic"] else ""}</td>'
            f'<td>{_pct(row["success_rate"])}</td><td>{row["average_score"]:.3f}</td>'
            f'<td>{row["average_steps"]:.2f}</td><td>{row["invalid_actions"]}</td>'
            f'<td>{"n/a" if row["recovery_ability"] is None else _pct(row["recovery_ability"])}</td><td>{row["runs"]}</td></tr>'
        )
    if not board_rows:
        board_rows.append('<tr><td colspan="8" class="empty">No runs yet.</td></tr>')
    cat_rows = []
    for row in data["categories"]:
        cat_rows.append(f'<tr><td>{html.escape(row["category"])}</td><td>{row["runs"]}</td><td>{_pct(row["success_rate"])}</td><td>{row["average_steps"]:.2f}</td><td>{row["invalid_actions"]}</td></tr>')
    if not cat_rows:
        cat_rows.append('<tr><td colspan="5" class="empty">No categories yet.</td></tr>')
    failure_rows = []
    max_failure = max((row["count"] for row in data["failure_breakdown"]), default=1)
    for row in data["failure_breakdown"]:
        width = max(2, round(row["count"] / max_failure * 100))
        failure_rows.append(f'<tr><td>{html.escape(row["type"])}</td><td><span class="bar" style="width:{width}%"></span></td><td>{row["count"]}</td></tr>')
    if not failure_rows:
        failure_rows.append('<tr><td colspan="3" class="empty">No failures recorded.</td></tr>')
    run_rows = []
    for row in data["runs"]:
        link = replay_links.get(row["run_id"])
        run_id = f'<a href="{html.escape(link, quote=True)}">{html.escape(row["run_id"])}</a>' if link else html.escape(row["run_id"])
        run_rows.append(f'<tr><td>{run_id}</td><td>{html.escape(row["agent_id"])}</td><td>{html.escape(row["task_id"])}</td><td>{html.escape(row["category"])}</td><td class="{"ok" if row["success"] else "bad"}">{"PASS" if row["success"] else "FAIL"}</td><td>{row["steps"]}</td></tr>')
    if not run_rows:
        run_rows.append('<tr><td colspan="6" class="empty">No runs yet.</td></tr>')
    payload = json.dumps(_jsonable(data), ensure_ascii=False).replace("<", "\\u003c")
    safe_title = html.escape(title)
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{safe_title}</title><style>
:root{{--bg:#0b1020;--panel:#141b2e;--panel2:#1a2440;--text:#e8edf8;--muted:#96a3bf;--accent:#66d9ef;--ok:#64d38a;--bad:#ff7c91;--line:#293653}}
*{{box-sizing:border-box}} body{{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}} header{{padding:25px 30px;border-bottom:1px solid var(--line);background:#0f162a}} h1{{margin:0 0 4px;font-size:25px}} .wrap{{max-width:1300px;margin:auto;padding:24px 28px}} .muted{{color:var(--muted)}}
.metrics{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:20px}} .metric,.panel{{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px}} .metric-label{{color:var(--muted);text-transform:uppercase;font-size:11px;letter-spacing:.07em}} .metric-value{{font-size:24px;font-weight:700;margin:4px 0}} .metric-detail{{color:var(--muted);font-size:12px}} .cols{{display:grid;grid-template-columns:1.35fr 1fr;gap:16px}} .panel{{margin-bottom:16px;overflow:auto}} h2{{font-size:16px;margin:0 0 12px}} table{{border-collapse:collapse;width:100%;white-space:nowrap}} th,td{{padding:9px 10px;border-bottom:1px solid var(--line);text-align:left}} th{{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}} tr:last-child td{{border-bottom:0}} .rank{{font-size:18px;color:var(--accent);font-weight:700}} .ok{{color:var(--ok);font-weight:600}} .bad{{color:var(--bad);font-weight:600}} .synthetic{{color:var(--accent);font-size:10px;border:1px solid var(--accent);border-radius:4px;padding:1px 4px;margin-left:5px}} .bar{{display:block;height:9px;border-radius:4px;background:linear-gradient(90deg,var(--bad),#ffb36b)}} .empty{{color:var(--muted);text-align:center;padding:22px}} a{{color:var(--accent)}} .foot{{color:var(--muted);font-size:12px;margin-top:15px}} @media(max-width:820px){{.wrap{{padding:15px}}.cols{{grid-template-columns:1fr}}}}
</style></head><body><header><div class="wrap" style="padding:0"><h1>{safe_title}</h1><div class="muted">Standardized environment benchmark · no private reasoning or real-world accounts</div></div></header><div class="wrap">
<section class="metrics">{cards}</section><div class="cols"><div><section class="panel"><h2>Tournament leaderboard</h2><table><thead><tr><th>#</th><th>Agent</th><th>Success</th><th>Score</th><th>Avg steps</th><th>Invalid</th><th>Recovery</th><th>Runs</th></tr></thead><tbody>{''.join(board_rows)}</tbody></table></section>
<section class="panel"><h2>Runs</h2><table><thead><tr><th>Run</th><th>Agent</th><th>Task</th><th>Category</th><th>Result</th><th>Steps</th></tr></thead><tbody>{''.join(run_rows)}</tbody></table></section></div>
<div><section class="panel"><h2>Task category</h2><table><thead><tr><th>Category</th><th>Runs</th><th>Success</th><th>Avg steps</th><th>Invalid</th></tr></thead><tbody>{''.join(cat_rows)}</tbody></table></section><section class="panel"><h2>Failure breakdown</h2><table><thead><tr><th>Failure type</th><th>Frequency</th><th>Count</th></tr></thead><tbody>{''.join(failure_rows)}</tbody></table></section></div></div>
<div class="foot">Synthetic/mock results are labeled and must not be interpreted as real-model performance. Data schema is available in <code>window.AGENT_ARENA_DATA</code>.</div></div>
<script>window.AGENT_ARENA_DATA={payload};</script></body></html>'''


def render_dashboard(runs: Iterable[Any], **kwargs: Any) -> str:
    """Short alias used by older scripts."""

    return render_dashboard_html(runs, **kwargs)


def render_html_report(runs: Iterable[Any], **kwargs: Any) -> str:
    """Report alias; dashboard and report share the same transparent data."""

    return render_dashboard_html(runs, **kwargs)


def write_report(
    runs: Iterable[Any],
    path: str | Path,
    *,
    title: str = "Agent Arena Report",
    replay_dir: str | Path | None = None,
) -> Path:
    """Write an HTML report and, optionally, one replay page per run.

    Replay files are linked from the run table when ``replay_dir`` is given.
    The function returns the report path for convenient CLI use.
    """

    path = Path(path)
    rows = _iter_runs(runs)
    links: dict[str, str] = {}
    if replay_dir is not None:
        replay_path = Path(replay_dir)
        replay_path.mkdir(parents=True, exist_ok=True)
        for item in rows:
            try:
                replay = item if isinstance(item, Replay) else Replay.from_run(item)
                filename = f"replay_{replay.run_id}.html".replace("/", "_").replace("\\", "_")
                ReplayViewer.write(replay, replay_path / filename)
                links[replay.run_id] = f"{replay_path.name}/{filename}" if replay_path.parent == path.parent else str(replay_path / filename)
            except Exception:
                # A malformed trace should not prevent the aggregate report
                # from being generated.
                continue
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_dashboard_html(rows, title=title, replay_links=links), encoding="utf-8")
    return path


def write_html_report(runs: Iterable[Any], path: str | Path, **kwargs: Any) -> Path:
    return write_report(runs, path, **kwargs)


def write_dashboard(runs: Iterable[Any], path: str | Path, **kwargs: Any) -> Path:
    return write_report(runs, path, **kwargs)


__all__ = [
    "normalise_run",
    "aggregate_metrics",
    "leaderboard",
    "build_dashboard_data",
    "render_dashboard_html",
    "render_dashboard",
    "render_html_report",
    "write_report",
    "write_html_report",
    "write_dashboard",
]
